Algoritmo "Entrada e Saída de Dados"

// Descrição   : Entrada e Saída de Dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2023
Var
// Seção de Declarações das variáveis
nome: caractere
nota: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual o seu nome?")
 leia(nome)
 escreval("Qual sua idade?")
 leia(nota)
 
 escreval("O seu nome é:", nome)
 escreval("A sua idade é:", nota)
 



Fimalgoritmo